### PR TITLE
print -> instead of \u2192 for arrows

### PR DESCRIPTION
**Pull request by nekopsykose**
for some reason it's printed as 1-wide but is actually two and looks
broken

### CODE REVIEW

**Comment by nekopsykose** [comment]
update: this is actually my broken fonts, but who uses unicode anyway? /s

**Comment by ptrcnull** [comment]
hm, would you be interested in making this configurable? either through the config or just relying on _some_ environmental variable

if not, i can just merge it anyway, the fancy arrows are not that important anyway

**Comment by nekopsykose** [comment]
that sounds like a lot of work

**Comment by ptrcnull** [comment]
wow that's a stale merge request

**Pull request merged**
